# Generated by Django 5.2.4 on 2025-07-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk_products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='silkproduct',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='silkproduct',
            name='type',
            field=models.CharField(choices=[('saree', 'Saree'), ('fabric', 'Fabric'), ('scarf', 'Scarf'), ('shawl', 'Shawl')], max_length=50),
        ),
    ]
